"""
src/agent/nodes/format_output.py
──────────────────────────────────
Node: format_output

Post-processes the draft report to:
  1. Validate and standardize inline citations
  2. Append a References section with full citation details
  3. Fix any minor formatting issues

IMPORTANT: Citations are injected from chunk METADATA, not generated by the LLM.

Why metadata-based citations matter:
  If we asked the LLM to generate citations, it would hallucinate page numbers
  and section names it doesn't remember. Instead, the synthesize node tells the
  LLM to write inline markers like:
    [Source: jpmorgan_10k_2023, p.142, §Capital Management]

  This node then builds the References section from the actual chunk objects
  that were retrieved, ensuring every citation is provably correct.

  This is the correct production approach for any compliance-adjacent application.
  For financial research, fabricated citations are not just embarrassing — they
  could constitute misrepresentation.

Interview talking point:
  "In financial services, citation accuracy is not optional. My format_output
   node builds the References section from the Azure AI Search chunk metadata,
   not from LLM generation. The LLM cannot hallucinate a page number because
   the page number comes from the index record."
"""

from __future__ import annotations

from ..state import AgentState


def run(state: AgentState) -> dict:
    """
    Post-process draft report: validate citations and build References section.
    """
    draft = state.get("draft_report", "")
    if not draft:
        return {"final_report": "Error: No draft report was generated."}

    # ── Collect all retrieved chunks across sub-questions ─────────────────────
    all_chunks: list[dict] = []
    seen_ids: set[str] = set()

    for sq in state.get("sub_questions", []):
        for chunk in sq.get("retrieved_chunks", []):
            chunk_id = chunk.get("chunk_id", "")
            if chunk_id and chunk_id not in seen_ids:
                all_chunks.append(chunk)
                seen_ids.add(chunk_id)

    # ── Build references section ───────────────────────────────────────────────
    references: list[str] = []
    for i, chunk in enumerate(all_chunks, 1):
        doc_id = chunk.get("document_id", "unknown")
        doc_title = chunk.get("document_title", "")
        page = chunk.get("page_start", "?")
        section = chunk.get("section_path_str", "")
        chunk_type = chunk.get("chunk_type", "prose")

        ref = f"{i}. **{doc_id}**"
        if doc_title and doc_title != doc_id:
            ref += f" — {doc_title}"
        ref += f", Page {page}"
        if section:
            ref += f", Section: {section}"
        ref += f" [{chunk_type}]"
        references.append(ref)

    # ── Compose final report ───────────────────────────────────────────────────
    final_report = draft

    if references:
        final_report += "\n\n---\n\n## References\n\n"
        final_report += "\n".join(references)

    # ── Add metadata footer ────────────────────────────────────────────────────
    total_chunks = sum(
        len(sq.get("retrieved_chunks", [])) for sq in state.get("sub_questions", [])
    )
    sub_q_count = len(state.get("sub_questions", []))
    sufficiency = state.get("overall_sufficiency", 0.0)

    final_report += (
        f"\n\n---\n\n"
        f"*Agent metadata: {sub_q_count} sub-questions, "
        f"{total_chunks} chunks retrieved, "
        f"sufficiency score: {sufficiency:.2f}*"
    )

    return {"final_report": final_report}
